version: '3.8'
services:
  jupyter:
    image: papersus/mini-pytorch:v1.0
    build: .
    ports:
      - "8888:8888"
      - "8889:8889"
      - "9000:9000"
    tty: true
    command: bash -c "source activate base && jupyter notebook --allow-root --ip=0.0.0.0 --no-browser"
